### ISSUE TITLE
Paper reading

### ISSUE THREAD

**Issue by ballZing** [ivivan/DualHeadSSIM#1]
Hello, is it convenient to provide the papers of your research work? I want to learn the results of your work，Thanks！

**Comment by ivivan** [comment]
Hi, this paper is just available online, [Imputation Paper](https://authors.elsevier.com/sd/article/S0168-1699(21)00394-X)

**Comment by ivivan** [comment]
> Hello, is it convenient to provide the papers of your research work? I want to learn the results of your work，Thanks！

Hi, this paper is just available online, [Imputation Paper](https://authors.elsevier.com/sd/article/S0168-1699(21)00394-X)
